services:
  db:
    container_name: test_project_db
    image: postgres
    env_file:
      - ./.env
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DB_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - redis
    volumes:
      - db_volume:/var/lib/postgresql/data

  db_test:
    container_name: test_project_db_test
    image: postgres
    environment:
      POSTGRES_DB: postgres_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5433:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - redis
    volumes:
      - db_test_volume:/var/lib/postgresql/data


  redis:
    container_name: test_project_redis
    image: redis
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - redis_volume:/data

volumes:
  db_volume:
  db_test_volume:
  redis_volume: